- neo/CMakeLists.txt
- neo/sys/win32/rc/dhewm3.rc
This adds an icon to win32 builds, as discussed in issue #115.
> Win32: Add an icon to the dhewm3 executable

- neo/idlib/math/Simd_SSE.cpp
This was checking the wrong variable so when count was < 4 it was writing
past the end of buffer and potentially breaking the stack.
> Fix stack overflow in SSE code

- neo/idlib/Str.h
Was calling memcpy with overlapping parameters which is inefficient,
undefined behavior and Valgrind complained about it.
> Fix idStr self-assignment

- neo/sys/linux/main.cpp
According to "man 2 readlink": "readlink() does not append a null byte to buf."
I have no idea how this worked up to now.
> Fix read from uninitialized part of buffer

- neo/d3xp/gamesys/SysCvar.cpp
- neo/game/gamesys/SysCvar.cpp
- neo/tools/compilers/aas/Brush.cpp
- neo/tools/compilers/aas/BrushBSP.cpp
- neo/tools/compilers/dmap/portals.cpp
- neo/tools/radiant/EditorBrush.cpp
- neo/tools/radiant/EditorEntity.cpp
- neo/tools/radiant/PARSE.CPP
- neo/ui/GuiScript.cpp
- s/allready/already
- s/Uknown/Unknown
- s/thier/their
Those are found during the build for the new Debian package (lintian informational messages)
Would be great if you could merge them to silence those.
Many thanks!
tobi (your dhewm3 package maintainer in Debian)
> Some spelling error fixes found during Debian build

- README.md
This pull request also renames OS X to macOS, which is the official name since 10.12 Sierra.
> Improve spelling and grammar in README

- neo/sound/snd_emitter.cpp
- neo/sound/snd_local.h
If an OpenAL source runs out of samples it transisions into state
AL_STOPPED. That happens if we're entering the menu (which switches
to another soundworld) and when saving the game (because the game
blocks for some milliseconds). Work around this by adding a new
field 'stopped' to the channel state and use that to determine if
a sound was stopped. And not AL_STOPPED like before.
> Fix entering the menu or saving the game stopping some sounds.

- neo/renderer/tr_main.cpp
...by including `vecLib/vecLib.h` only on `__APPLE__`, and not just any `__ppc__`
From https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=235668:
> On powerpc* platforms vecLib/vecLib.h is included by default.
> This header is only available on Mac OS X, so remove it. It
> doesn't seem to be actually needed to compile this port.
> Fix build on powerpc but not mac

- neo/sound/snd_cache.cpp
Not a real fix. Sufficient to avoid the issue for my play sessions tho. :)
> ignore errors unloading OpenAL data. mitigates #178

- neo/framework/Common.cpp
- neo/framework/Session.cpp
- neo/sound/snd_system.cpp
- neo/sound/snd_world.cpp
For some reason sounds were only updated/started about every 100ms, which could lead to delays of up to around 100ms after a sound gets started (with `idSoundEmitterLocal::StartSound()`) until OpenAL is finally told to play the sound.
Also, the actual delay drifted over time between 1ms and 100ms, as the sound ticks weren't a fixed multiple of the (16ms) gameticks - and the sound updates didn't even happen at the regular 92-94ms intervals they should because they run in the async thread which only updates every
16ms...
Because of this, the machine gun and other rapid firing weapons sounded like they shot in bursts or left out shots occasionally, even though they don't.
Anyway, now sound is updated every 16ms in the async thread so delays are <= 16ms and hopefully a lot less noticeable. …
> Update sounds at ~60Hz instead of ~10Hz, fixes #141

- neo/CMakeLists.txt
- neo/d3xp/Game_local.cpp
- neo/d3xp/Game_local.h
- neo/d3xp/gamesys/SaveGame.cpp
- neo/d3xp/gamesys/SaveGame.h
- neo/d3xp/physics/Physics_Player.cpp
- neo/d3xp/script/Script_Compiler.cpp
- neo/d3xp/script/Script_Program.cpp
- neo/d3xp/script/Script_Program.h
- neo/framework/BuildVersion.h
- neo/framework/Common.cpp
- neo/framework/Licensee.h
- neo/framework/Session.cpp
- neo/game/Game_local.cpp
- neo/game/Game_local.h
- neo/game/gamesys/SaveGame.cpp
- neo/game/gamesys/SaveGame.h
- neo/game/physics/Physics_Player.cpp
- neo/game/script/Script_Compiler.cpp
- neo/game/script/Script_Program.cpp
- neo/game/script/Script_Program.h
Now savegames from before c4c72363523fc65e635c7ad7ae86247b4f082340 can be loaded properly again.
Bumped the `BUILD_NUMBER` and changed the savegameformat a bit by adding information about the dhewm3 build and system the savegame was created on (of course compatibility with old savegames persists).
See #344 for more information about the issues
> Fix script checksum in savegames, enhance savegames, fix clipping bugs in delta1

- neo/framework/async/AsyncClient.cpp
Using #ifdef was a problem because even if ID_ENFORCE_KEY_CLIENT was set to 0, the #ifdef will still compile anything inside that block. _(#ifdef is not the same as #if)_
I am doing this pull request because it is a problem I faced before. Every person who wants to play dhewm3 multiplayer, as client, always needs to introduce a cdkey even if this is a GPL release.
> fix: cdkey check now properly disabled in clients

- neo/renderer/tr_render.cpp
- neo/sound/snd_world.cpp
Found with Valgrind. These might have triggered unpredictable behavior in sound or rendering.
> Fix some uninitialized member variables

- Changelog.md
- README.md
- neo/d3xp/script/Script_Compiler.cpp
- neo/framework/Console.cpp
- neo/framework/EditField.cpp
- neo/framework/KeyInput.cpp
- neo/framework/KeyInput.h
- neo/game/script/Script_Compiler.cpp
- neo/sys/events.cpp
- neo/sys/sys_public.h
- neo/ui/EditWindow.cpp
If a key is pressed whichs SDL_Keycode isn't known to Doom3 (has no
corresponding K_* constant), its SDL_Scancode is mapped to the
corresponding newly added K_SC_* scancode constant.
I think I have K_SC_* constants for all keys that differ between
keyboard layouts (which is mostly printable characters; F1-F12, Ctrl,
Shift, ... should be the same on all layouts, which means that e.g.
SDL_SCANCODE_F1 always belongs to SDLK_F1 which the old code already
maps to Doom3's K_F1).
What's extra nice (IMO) is that when Doom3 requests a *localized* name
of the key (like for showing in the bindings menu), we actually use the
name of the SDL_Keycode that *currently* belongs to the scancode, and
esp. the "Western High-ASCII characters" (ISO-8859-1) supported by Doom3
like Ä or Ñ are displayed …
> Support (hopefully) all keyboard keys via scancodes

- neo/d3xp/ai/AI_pathing.cpp
- neo/d3xp/gamesys/SysCvar.cpp
- neo/game/ai/AI_pathing.cpp
- neo/game/gamesys/SysCvar.cpp
- neo/sys/win32/rc/Radiant.rc
- neo/tools/af/DialogAFBody.cpp
(spotted while looking at some `cvar` definitions)
> Fixup: typo: 'hiehgt' -> 'height' in a few places around the codebase

- neo/ui/Window.cpp
Replaced K_JOY1 and K_JOY2 (which no longer exists in KeyInput.cpp and KeyInput.h) with its current equivalent K_JOY_BTN_SOUTH and K_JOY_BTN_EAST respectively. I do not know whether or not those are the actual names you want to replace K_JOY1 and K_JOY2, but had to make a very good guess to make the code buildable.
> Modified some code to make it compilable.

- neo/sys/platform.h
After 6f35ce045dd3ab57cac053301b1ebac4d5270501 commit compilation on mcst-lcc became problematic (compiler does not support __builtin_alloca_with_align). Added workaround for < 1.28 version.
Ref: http://mcst.ru/lcc
> Workaround for MCST-LCC compiler < 1.28 version

- neo/framework/KeyInput.cpp
- neo/framework/KeyInput.h
added a simple helper print method to know what key/button is being pressed, controlled via a bool cvar "in_namePressed" 1 or 0, I tested it and it works with keyboard, mouse and gamepad.
> added a simple printing of the key/button pressed

- dist/linux/share/applications/org.dhewm3.Dhewm3.d3xp.desktop
- dist/linux/share/applications/org.dhewm3.Dhewm3.desktop
"desktop-file-validate" reports the following error:
org.dhewm3.Dhewm3.desktop: error: value "dhewm3 "$@"" for key "Exec" in group "Desktop Entry" contains a non-escaped character '$' in a quote, but it should be escaped with two backslashes ("\\$")
see
https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html#exec-variables
> Fix desktop files

- neo/framework/Common.cpp
This allows me to distribute the app bundle with the game dylibs but still look for the game data in Application Support
> On macOS, look for the game dylib in the app bundle

- neo/CMakeLists.txt
- neo/d3xp/Game_local.cpp
- neo/framework/Common.cpp
- neo/framework/Dhewm3SettingsMenu.cpp
- neo/game/Game_local.cpp
- neo/idlib/Lib.cpp
- neo/renderer/qgl.h
- neo/renderer/tr_backend.cpp
- neo/renderer/tr_local.h
- neo/sound/snd_decoder.cpp
- neo/sound/stbvorbis_impl.c
- neo/sys/cpu.cpp
- neo/sys/events.cpp
- neo/sys/glimp.cpp
- neo/sys/linux/main.cpp
- neo/sys/osx/DOOMController.mm
- neo/sys/osx/SDLMain.m
- neo/sys/posix/posix_main.cpp
- neo/sys/sys_imgui.cpp
- neo/sys/sys_sdl.h
- neo/sys/threads.cpp
- neo/sys/win32/SDL_win32_main.c
- neo/sys/win32/win_main.cpp
- neo/tools/debugger/DebuggerServer.cpp
- neo/tools/debugger/DebuggerServer.h
Port dhewm3 to SDL3, while still supporting SDL2 and even SDL1.2.
Seems to work well on Linux (and probably BSD and similar), but other platforms are still TODO.
Will probably only make Windows work and try to make Mac work; no idea if SDL3 (or SDL2, for that matter..) even supports AROS.
> Support SDL3

- neo/framework/Common.cpp
- neo/idlib/Heap.h
- neo/renderer/ModelOverlay.cpp
- neo/renderer/Model_md5.cpp
- neo/renderer/tr_light.cpp
- neo/renderer/tr_trisurf.cpp
- neo/sys/platform.h
- neo/sys/win32/win_main.cpp
The use of plain alloca() causes stack overflows (or assertions meant to prevent them) when models with many polys are loaded, see #528 
Mem_MallocA() is a macro that that uses _alloca16() for allocations < 1MB, and otherwise uses Mem_Alloc16(). It should be used together with Mem_FreeA() to free the memory if it came from Mem_Alloc16(). A `bool` variable must be passed to Mem_MallocA() and Mem_FreeA(), it will be set to true if _alloca16() was used and false otherwise, and Mem_FreeA() uses it to do the right thing.
This is kinda like [Microsoft's _malloca() and _freea()](https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/malloca?view=msvc-170), except that doesn't need the additional bool because they can do platform-specific magic to detect whether memory is on the stack. …
> Introduce Mem_MallocA() that is like alloca() but falls back to heap memory for bigger allocations

- neo/d3xp/PlayerView.cpp
- neo/framework/Licensee.h
- neo/framework/Session.cpp
- neo/game/PlayerView.cpp
- neo/ui/DeviceContext.cpp
- neo/ui/DeviceContext.h
- neo/ui/SimpleWindow.cpp
- neo/ui/SimpleWindow.h
- neo/ui/Window.cpp
- neo/ui/Window.h
As requested in #324.
You won't see any difference unless you use CstDoom3's GUI files. But note that you can't just use their .pk4 files, because they contain other things incompatible with dhewm3 (I didn't port any gameplay changes from CstDoom3).
For the basegame I prepared this .pk4 (**rename the .zip to .pk4 after download**, Github doesn't support attaching .pk4 files): [z_cstd3_guis.zip](https://github.com/user-attachments/files/18462597/z_cstd3_guis.zip)
It's for the base game, so put it into `Doom3/base/`, next to `pak000.pk4` etc.
Also note that old savegames will stop working once you add `z_cstd3_guis.pk4`.
I'd appreciate if someone else could create cleaner .pk4s with .gui files for both the base game and d3xp and upload them somewhere, so I can link them on the dhewm3 page …
> Support CstDoom3 GUIs for aspect-ratio-independent HUD

- neo/cm/CollisionModel_translate.cpp
somehow the collision code managed to spread NaNs on Win32, which caused a horrible framerate, "GetPointOutsideObstacles: no valid point found" warnings in the console and assertions in debug builds. Didn't happen in Vanilla Doom3 though.
At the location I changed the code in, I saw the following values in the debugger:
normal: {x=0.00610326231 y=5.58793545e-09 z=1.19209290e-07 } trmEdge->start: {x=-1358.00000 y=913.948975 z=25.2637405 } start: {x=-1358.00000 y=916.000000 z=34.0000000 }
end:   {x=-1358.00000 y=810.000000 z=34.0000000 }
dist (normal*trmEdge->start): -8.28822231
d1: 9.53674316e-07
d2: 9.53674316e-07
f1 (d1/(d1-d2)): inf
"normal" isn't normalized and also very small (in all directions), "start" and "end" have quite different y values, but still doing scalar multiplications …
> Fix issues in first map of the "UAC Franchise 666" user campaign, #651

- neo/CMakeLists.txt
Using O3 option on [E2K](https://en.wikipedia.org/wiki/Elbrus_(computer)) mcst-lcc compiler approximately equal to O2 at X86/ARM gcc.
> neo/CMakeLists.txt: added use of O3 instead of O2 for e2k arch

- neo/idlib/math/Ode.cpp
This PR fixes an issue in the `idODE_Midpoint` destructor where dynamically allocated arrays were incorrectly deallocated using `delete` instead of `delete[]`, leading to undefined behavior.
> Fix memory deallocation issue by using delete[] for arrays

- Changelog.md
- neo/framework/Common.cpp
- neo/framework/Dhewm3SettingsMenu.cpp
- neo/renderer/Image.h
- neo/renderer/Image_init.cpp
- neo/renderer/Image_load.cpp
- neo/renderer/RenderSystem.h
- neo/renderer/RenderSystem_init.cpp
- neo/renderer/qgl.h
Based on https://github.com/dhewm/dhewm3/issues/447#issuecomment-2254369525
So far I haven't tested this.
The post with the patch said
>  for some reason BC7's compressed with compressonator don't work, only nvidia texture tools 2.1.2(or my special version 2.1.3) is working, alpha channels are working also (nvcompress.exe -bc7 -alpha ...)
If anyone has a DDS file with BC7 file from compressonator I could try to debug that.
Generally testing (ideally with DDS files from different tools!) is very welcome!
Note that:
* You probably don't want to use this for normalmaps, continue using RXGB DXT5 for that
- The *compressonator* format name for this is `DXT5_xGBR`, used like `compressonator -fd DXT5_xGBR in.tga out.dds`
- **Update:** Ok, you *can* use BC7 for normalmaps, but only if you use my …
> Support BPTC (BC7) textures

- Changelog.md
- Configuration.md
- neo/framework/Dhewm3SettingsMenu.cpp
- neo/renderer/Image.h
- neo/renderer/Image_init.cpp
- neo/renderer/Image_load.cpp
Allow configuring "Only use precompressed textures if they're BPTC (BC7)" by setting `image_usePrecompressedTextures 2`.
Also allow configuring "compress uncompressed textures to BPTC on upload to GPU" by setting `image_useCompression 2`.
And expose that in the Dhewm3SettingsMenu
> Allow configuring "Only use precompressed textures if they're BPTC (BC7)"
